# file: roles/rl-ovh-templates--list/tasks/main.yml
---

- name: Get list of ovh installationTemplates
  ovh: service='list' name='ovh_installation_templates'
  register: ovh_templates


- name: Get list of custom templates
  ovh: service='list' name='templates'
  register: custom_templates

