# file: roles/rl-ovh-servers-list/tasks/main.yml
---

- debug:
    var: ansible_distribution

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
#- name: Get list of servers
#  ovh: service='list' name='dedicated'
#  register: servers

