# file: roles/rl-ovh-servers-list/tasks/main.yml
---

- debug:
    var: ansible_distribution

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: Get list of servers
  ovh: service='list' name='dedicated' endpoint='soyoustart-eu' application_key='Baiph8Aingoh5Aeb' application_secret='$1$06e5cda925dcb86b80d8d320c1a6df24db3a25cb' consumer_key='Z3FuycieqnPkL4xH2mQEZGdzhnHN1PD9'
  register: servers

