# file: roles/rl-ovh-dedicated-server-deploy/tasks/main.yml
---

- name: Get list of servers
  ovh: service='list' name='dedicated' endpoint="{{ datacenter_endpoint }}" application_key="{{ application_key }}" application_secret="{{ application_secret }}" consumer_key="{{ consumer_key }}"
  register: servers

