# file: roles/rl-ovh-servers-list/tasks/main.yml
---

- debug:
    var: ansible_distribution

- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: Get list of servers
  ovh: service='list' name='dedicated' endpoint='soyoustart-eu' application_key='siGKuxM0z76QGlaL' application_secret='JHzCcEA6NP2hm9YEPT7xVs6wxspe5vlK'
  register: servers

